version: '3.3'
services:
    
    
            
    redis:
        image: 'bitnami/redis:latest'            
        container_name: redis
        deploy:
            replicas: 1
        environment:
           - ALLOW_EMPTY_PASSWORD=yes
           - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL       
           - net.core.somaxconn=511
           - vm.overcommit_memory=1
        labels:
           kompose.service.type: nodeport

        ports:
            - '6379:6379'         
        networks:
            - unicorn
            
   
 
    web:
        image: web 
        build: ./web 
        container_name: web
        deploy:
            replicas: 1 
        links:
            - redis
        ports:
            - '9595:8080'       
        networks:
            - unicorn           

            
networks:
    unicorn:
        driver: bridge
